export const mockProducts = [
    {
        id: "1",
        title: "Noir Structured Blazer",
        price: "289.00",
        compareAtPrice: "350.00",
        vendor: "STRUXLY STUDIO",
        type: "Blazer",
        image: null,
        gradient: "from-violet-900/60 to-slate-900",
        tags: ["new-arrival", "bestseller"],
        description: "A sharp, tailored blazer with modern proportions and premium wool blend.",
    },
    {
        id: "2",
        title: "Essential Cotton Tee",
        price: "89.00",
        compareAtPrice: null,
        vendor: "STRUXLY BASICS",
        type: "T-Shirt",
        image: null,
        gradient: "from-cyan-900/60 to-slate-900",
        tags: ["essential", "bestseller"],
        description: "Heavyweight premium cotton, relaxed fit. The foundation of any wardrobe.",
    },
    {
        id: "3",
        title: "Silk Drape Maxi Dress",
        price: "420.00",
        compareAtPrice: "520.00",
        vendor: "STRUXLY ATELIER",
        type: "Dress",
        image: null,
        gradient: "from-rose-900/60 to-slate-900",
        tags: ["new-arrival", "limited"],
        description: "Flowing silk charmeuse with a draped neckline. Evening elegance reimagined.",
    },
    {
        id: "4",
        title: "Urban Runner Sneakers",
        price: "195.00",
        compareAtPrice: null,
        vendor: "STRUXLY SPORT",
        type: "Footwear",
        image: null,
        gradient: "from-emerald-900/60 to-slate-900",
        tags: ["trending"],
        description: "Engineered mesh upper with responsive cushioning. Street to studio.",
    },
    {
        id: "5",
        title: "Waxed Canvas Tote",
        price: "145.00",
        compareAtPrice: "175.00",
        vendor: "STRUXLY ACCESSORIES",
        type: "Bag",
        image: null,
        gradient: "from-amber-900/60 to-slate-900",
        tags: ["sustainable"],
        description: "Water-resistant waxed cotton with leather trim. Carries your world in style.",
    },
    {
        id: "6",
        title: "Tailored Linen Trousers",
        price: "210.00",
        compareAtPrice: null,
        vendor: "STRUXLY STUDIO",
        type: "Trousers",
        image: null,
        gradient: "from-indigo-900/60 to-slate-900",
        tags: ["new-arrival"],
        description: "Relaxed wide-leg linen with a high waist. Effortless summer sophistication.",
    },
    {
        id: "7",
        title: "Cashmere Half-Zip",
        price: "340.00",
        compareAtPrice: "420.00",
        vendor: "STRUXLY ATELIER",
        type: "Knitwear",
        image: null,
        gradient: "from-stone-800/60 to-slate-900",
        tags: ["limited", "bestseller"],
        description: "100% Grade A Mongolian cashmere. The luxury layer for every season.",
    },
    {
        id: "8",
        title: "Oversized Denim Jacket",
        price: "265.00",
        compareAtPrice: null,
        vendor: "STRUXLY STUDIO",
        type: "Jacket",
        image: null,
        gradient: "from-blue-900/60 to-slate-900",
        tags: ["trending", "new-arrival"],
        description: "Japanese selvedge denim, vintage wash. A statement piece that only gets better.",
    },
];

export const mockStoreInfo = {
    name: "STRUXLY FASHION HOUSE",
    domain: "struxly-fashion.myshopify.com",
    currency: "USD",
    productCount: mockProducts.length,
    collections: ["New Arrivals", "Bestsellers", "Limited Edition", "Essentials"],
};
